[project]
name = "sfera"
version = "0.1.0"
description = "Service Center & Metrology Laboratory"
requires-python = ">=3.12"

[tool.black]
line-length = 88
target-version = ["py312"]

[tool.isort]
profile = "black"
line_length = 88

[tool.ruff]
line-length = 88
target-version = "py312"

[tool.ruff.lint]
select = [
    "E",
    "F",
    "I",
    "UP",
    "B",
]

extend-ignore = [
    "B008",
]

[tool.pytest.ini_options]
pythonpath = [
    "."
]

testpaths = [
    "tests"
]

python_files = [
    "test_*.py"
]

addopts = [
    "--import-mode=importlib"
]
