"""create initial sfera models

Revision ID: b57f770d88ad
Revises: 72485e49cfd8
Create Date: 2026-07-07 17:47:14.514909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b57f770d88ad'
down_revision: Union[str, Sequence[str], None] = '72485e49cfd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_templates',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('document_type', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('template_path', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('materials',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('article', sa.String(length=100), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('article')
    )
    op.create_table('methodologies',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=True),
    sa.Column('document_number', sa.String(length=100), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('permissions',
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('price_lists',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('warehouses',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('responsible_person', sa.String(length=255), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('price_list_items',
    sa.Column('price_list_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('service_type', sa.String(length=100), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['price_list_id'], ['price_lists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role_permissions',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('warehouse_stocks',
    sa.Column('warehouse_id', sa.UUID(), nullable=False),
    sa.Column('material_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('reserved_quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('instrument_labels',
    sa.Column('instrument_id', sa.UUID(), nullable=False),
    sa.Column('label_type', sa.Enum('QR', 'BARCODE', 'DATAMATRIX', name='labeltype'), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('replacement_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('value')
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('order_id', sa.UUID(), nullable=True),
    sa.Column('document_template_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['document_template_id'], ['document_templates.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('production_movements',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('stage', sa.Enum('RECEIVED', 'REGISTRATION', 'DIAGNOSTIC', 'REPAIR', 'VERIFICATION', 'QUALITY_CONTROL', 'ISSUANCE', name='productionstage'), nullable=False),
    sa.Column('responsible_user_id', sa.Uuid(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('warehouse_movements',
    sa.Column('warehouse_id', sa.UUID(), nullable=False),
    sa.Column('material_id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=True),
    sa.Column('movement_type', sa.Enum('RECEIPT', 'ISSUE', 'RESERVATION', 'RELEASE', 'ADJUSTMENT', name='movementtype'), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('diagnostics',
    sa.Column('order_item_id', sa.UUID(), nullable=False),
    sa.Column('conclusion', sa.Text(), nullable=True),
    sa.Column('recommendation', sa.Enum('NO_ISSUES', 'REPAIR_REQUIRED', 'REPLACEMENT_RECOMMENDED', 'REPAIR_NOT_ECONOMIC', 'WRITE_OFF', 'RETURN_TO_MANUFACTURER', name='recommendation'), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('repairs',
    sa.Column('order_item_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'IN_WORK', 'WAITING', 'COMPLETED', 'CANCELLED', name='repairstatus'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('arshin_exports',
    sa.Column('verification_id', sa.UUID(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('exported_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('exported_by', sa.Uuid(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['verification_id'], ['verifications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('customers', sa.Column('name', sa.String(length=255), nullable=False))
    op.add_column('customers', sa.Column('contact_person', sa.String(length=255), nullable=True))
    op.add_column('customers', sa.Column('phone', sa.String(length=50), nullable=True))
    op.add_column('customers', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('customers', sa.Column('comment', sa.Text(), nullable=True))
    op.add_column('instrument_types', sa.Column('model', sa.String(length=255), nullable=True))
    op.add_column('instrument_types', sa.Column('measurement_type', sa.String(length=255), nullable=True))
    op.add_column('instrument_types', sa.Column('accuracy_class', sa.String(length=100), nullable=True))
    op.add_column('instrument_types', sa.Column('verification_interval_months', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('instrument_types_name_key'), 'instrument_types', type_='unique')
    op.drop_column('instrument_types', 'short_name')
    op.drop_column('instrument_types', 'registry_number')
    op.add_column('instruments', sa.Column('factory_number', sa.String(length=100), nullable=True))
    op.add_column('instruments', sa.Column('manufacture_year', sa.Integer(), nullable=True))
    op.alter_column('instruments', 'instrument_type_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('instruments', 'registry_number',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('instruments', 'modification',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.drop_index(op.f('ix_instruments_instrument_type_id'), table_name='instruments')
    op.drop_index(op.f('ix_instruments_registry_number'), table_name='instruments')
    op.drop_index(op.f('ix_instruments_serial_number'), table_name='instruments')
    op.drop_column('instruments', 'owner')
    op.drop_column('instruments', 'instrument_name')
    op.drop_column('instruments', 'is_active')
    op.drop_column('instruments', 'manufacturer')
    op.drop_column('instruments', 'year_of_manufacture')
    op.add_column('order_items', sa.Column('line_number', sa.Integer(), nullable=False))
    op.add_column('order_items', sa.Column('customer_inventory_number', sa.String(length=100), nullable=True))
    op.add_column('order_items', sa.Column('customer_comment', sa.Text(), nullable=True))
    op.drop_index(op.f('ix_order_items_instrument_id'), table_name='order_items')
    op.drop_column('order_items', 'modification')
    op.drop_column('order_items', 'instrument_name')
    op.drop_column('order_items', 'quantity')
    op.drop_column('order_items', 'registry_number')
    op.drop_column('order_items', 'note')
    op.drop_column('order_items', 'serial_number')
    op.drop_column('order_items', 'status')
    op.add_column('orders', sa.Column('number', sa.String(length=50), nullable=False))
    op.add_column('orders', sa.Column('received_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('orders', sa.Column('planned_issue_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('orders', sa.Column('issued_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_constraint(op.f('orders_order_number_key'), 'orders', type_='unique')
    op.create_unique_constraint(None, 'orders', ['number'])
    op.drop_column('orders', 'order_number')
    op.drop_column('orders', 'accepted_at')
    op.drop_column('orders', 'closed_at')
    op.add_column('organizations', sa.Column('name', sa.String(length=255), nullable=False))
    op.add_column('organizations', sa.Column('website', sa.String(length=255), nullable=True))
    op.add_column('organizations', sa.Column('comment', sa.Text(), nullable=True))
    op.alter_column('organizations', 'short_name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               nullable=True)
    op.drop_index(op.f('ix_organizations_inn'), table_name='organizations')
    op.create_unique_constraint(None, 'organizations', ['name'])
    op.create_unique_constraint(None, 'organizations', ['inn'])
    op.drop_column('organizations', 'active')
    op.drop_column('organizations', 'full_name')
    op.add_column('verifications', sa.Column('methodology', sa.String(length=255), nullable=True))
    op.add_column('verifications', sa.Column('export_to_arshin', sa.Boolean(), nullable=False))
    op.add_column('verifications', sa.Column('exported_to_arshin', sa.Boolean(), nullable=False))
    op.drop_constraint(op.f('verifications_methodology_id_fkey'), 'verifications', type_='foreignkey')
    op.drop_column('verifications', 'arshin_export_enabled')
    op.drop_column('verifications', 'arshin_exported')
    op.drop_column('verifications', 'certificate_number')
    op.drop_column('verifications', 'methodology_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verifications', sa.Column('methodology_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('verifications', sa.Column('certificate_number', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('verifications', sa.Column('arshin_exported', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('verifications', sa.Column('arshin_export_enabled', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('verifications_methodology_id_fkey'), 'verifications', 'verification_methods', ['methodology_id'], ['id'])
    op.drop_column('verifications', 'exported_to_arshin')
    op.drop_column('verifications', 'export_to_arshin')
    op.drop_column('verifications', 'methodology')
    op.add_column('organizations', sa.Column('full_name', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
    op.add_column('organizations', sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'organizations', type_='unique')
    op.drop_constraint(None, 'organizations', type_='unique')
    op.create_index(op.f('ix_organizations_inn'), 'organizations', ['inn'], unique=False)
    op.alter_column('organizations', 'short_name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('organizations', 'comment')
    op.drop_column('organizations', 'website')
    op.drop_column('organizations', 'name')
    op.add_column('orders', sa.Column('closed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('accepted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('order_number', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'orders', type_='unique')
    op.create_unique_constraint(op.f('orders_order_number_key'), 'orders', ['order_number'], postgresql_nulls_not_distinct=False)
    op.drop_column('orders', 'issued_at')
    op.drop_column('orders', 'planned_issue_at')
    op.drop_column('orders', 'received_at')
    op.drop_column('orders', 'number')
    op.add_column('order_items', sa.Column('status', postgresql.ENUM('RECEIVED', 'IN_DIAGNOSTIC', 'IN_VERIFICATION', 'IN_REPAIR', 'WAITING', 'COMPLETED', 'ISSUED', name='orderitemstatus'), autoincrement=False, nullable=False))
    op.add_column('order_items', sa.Column('serial_number', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('order_items', sa.Column('note', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('order_items', sa.Column('registry_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('order_items', sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('order_items', sa.Column('instrument_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('order_items', sa.Column('modification', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_order_items_instrument_id'), 'order_items', ['instrument_id'], unique=False)
    op.drop_column('order_items', 'customer_comment')
    op.drop_column('order_items', 'customer_inventory_number')
    op.drop_column('order_items', 'line_number')
    op.add_column('instruments', sa.Column('year_of_manufacture', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('instruments', sa.Column('manufacturer', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('instruments', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('instruments', sa.Column('instrument_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('instruments', sa.Column('owner', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_instruments_serial_number'), 'instruments', ['serial_number'], unique=False)
    op.create_index(op.f('ix_instruments_registry_number'), 'instruments', ['registry_number'], unique=False)
    op.create_index(op.f('ix_instruments_instrument_type_id'), 'instruments', ['instrument_type_id'], unique=False)
    op.alter_column('instruments', 'modification',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('instruments', 'registry_number',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('instruments', 'instrument_type_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('instruments', 'manufacture_year')
    op.drop_column('instruments', 'factory_number')
    op.add_column('instrument_types', sa.Column('registry_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('instrument_types', sa.Column('short_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('instrument_types_name_key'), 'instrument_types', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_column('instrument_types', 'verification_interval_months')
    op.drop_column('instrument_types', 'accuracy_class')
    op.drop_column('instrument_types', 'measurement_type')
    op.drop_column('instrument_types', 'model')
    op.drop_column('customers', 'comment')
    op.drop_column('customers', 'email')
    op.drop_column('customers', 'phone')
    op.drop_column('customers', 'contact_person')
    op.drop_column('customers', 'name')
    op.create_table('verification_methods',
    sa.Column('code', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('archived', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('verification_methods_pkey')),
    sa.UniqueConstraint('code', name=op.f('verification_methods_code_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('arshin_exports')
    op.drop_table('repairs')
    op.drop_table('diagnostics')
    op.drop_table('warehouse_movements')
    op.drop_table('production_movements')
    op.drop_table('documents')
    op.drop_table('user_roles')
    op.drop_table('instrument_labels')
    op.drop_table('warehouse_stocks')
    op.drop_table('users')
    op.drop_table('role_permissions')
    op.drop_table('price_list_items')
    op.drop_table('warehouses')
    op.drop_table('roles')
    op.drop_table('price_lists')
    op.drop_table('permissions')
    op.drop_table('methodologies')
    op.drop_table('materials')
    op.drop_table('document_templates')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
