"""add price list metadata fields

Revision ID: be6d8dc2f696
Revises: 5def9c7caf65
Create Date: 2026-08-06 19:36:16.590403

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "be6d8dc2f696"
down_revision: str | Sequence[str] | None = "5def9c7caf65"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""

    op.add_column(
        "price_lists",
        sa.Column(
            "price_list_type",
            sa.String(length=100),
            nullable=False,
        ),
    )

    op.add_column(
        "price_lists",
        sa.Column(
            "currency",
            sa.String(length=10),
            nullable=False,
        ),
    )

    op.add_column(
        "price_lists",
        sa.Column(
            "valid_from",
            sa.Date(),
            nullable=True,
        ),
    )

    op.add_column(
        "price_lists",
        sa.Column(
            "valid_to",
            sa.Date(),
            nullable=True,
        ),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("price_lists", "valid_to")
    op.drop_column("price_lists", "valid_from")
    op.drop_column("price_lists", "currency")
    op.drop_column("price_lists", "price_list_type")
    # ### end Alembic commands ###
